import uuid

from sqlalchemy import Boolean, Enum, ForeignKey, Numeric, String, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.session import Base

event_item_type_enum = Enum(
    "auction", "lucky_draw_on_stage", "lucky_draw", name="event_item_type"
)
event_item_status_enum = Enum("received", "not_received", name="event_item_status")


class EventItem(Base):
    """Auction & lucky draw items (Story 14.1/14.6). `lot_ref` (A-1, A-2… /
    L-1, L-2…, sequential per event, reset per event) is generated by the
    application layer when Story 14.6 builds the create flow — out of scope
    for this data-model-only story, so it's a plain nullable column here."""

    __tablename__ = "event_items"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("events.id", ondelete="CASCADE"), nullable=False
    )
    lot_ref: Mapped[str | None] = mapped_column(String(20))
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    value_hkd: Mapped["Numeric | None"] = mapped_column(Numeric(10, 2))
    donor_sponsor: Mapped[str | None] = mapped_column(String(200))
    contact_rotary_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("members.id", ondelete="SET NULL")
    )
    item_type: Mapped[str] = mapped_column(event_item_type_enum, nullable=False)
    ad_page: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    status: Mapped[str] = mapped_column(
        event_item_status_enum, nullable=False, server_default="not_received"
    )
    # Auction items only — nullable, populated once the item actually sells.
    value_sold: Mapped["Numeric | None"] = mapped_column(Numeric(10, 2))
