"""members rotarian_since and photo_url

Revision ID: 0c3ca6fbc5aa
Revises: 8ee54c159ce3
Create Date: 2026-07-05 12:38:50.370433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3ca6fbc5aa'
down_revision: Union[str, Sequence[str], None] = '8ee54c159ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('rotarian_since', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'photo_url')
    op.drop_column('members', 'rotarian_since')
    # ### end Alembic commands ###
