"""email_log has_attachments

Revision ID: b7f912f4d812
Revises: 0c3ca6fbc5aa
Create Date: 2026-07-05 14:13:11.365009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f912f4d812'
down_revision: Union[str, Sequence[str], None] = '0c3ca6fbc5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('has_attachments', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_log', 'has_attachments')
    # ### end Alembic commands ###
